prepare:
    fetch:
    - url: https://raw.githubusercontent.com/kei-ito/editor-settings/master/.eslintrc.js
    path: .eslintrc.js
engines:
    duplication:
        enabled: true
        exclude_paths:
            - "test/**"
        config:
            languages:
                - javascript
    eslint:
        enabled: true
        config:
            config: .eslintrc.js
    fixme:
        enabled: true
ratings:
    paths:
        - "**.js"
