language: node_js
node_js:
- '9'
- '8'
- '7'
- '6'
install:
- npm install
- npm install -g nyc eslint
script:
- npm run test_coverage
- npm run lint
after_success:
- npm install -g codecov
- codecov
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: YG99Ha7DdLyEcDoByPXuHp0wM7J5bQltFhS4OMtTwFTRI2dIDRs8IrERwzr9n1mtc4l6xtdSgU2uBS0QaozUlNEn7OUN9HenDdP9OTpWXggpGdVtyiWoIsTU/SpnnTTfdHVrD6LJ5Bad1ur9hK67ZXKQIn15iloY7ik4eLNQjRz2sDrQwtQeCCT0EPO4a7GrqdDLnxrMj7Snk/OG1NxoBWxM93dXb8CMvaEUzsrjnI35VLr+9DMCI4dLR7vhs0VEm36d97e98Nfg6T2owSxOwOWP4z8S56vioYfhRwkKEs+h/CjC0sTXrWXJBSGGRv/IDWVNUwULwIe1jWjJVnPBV4nIwKdiBPeQHkS7rvdbUFwbf09F+/rwBNs8TehjmR3IJ6WsHWSAK1xJioMAlxC2hWFoam8qfOV5T56hZCKz02EKEcoeiKqdqAoAW8D1m56Gpty3XHWiSU6Cvx5FADetFJp0ayWHor3k7/xKOXBlOoZ0aR6jybd28rPogPRl7rz0gU8ZSCwfQWtX2rPSSf30MaE/BIiyMTxdnX+SuXy6cVrg6epE2OlD5aZezFj8NQVU25PL2PyHrsdSPoR6BETjMc4YUKpsXUj4ae2iyzBt/zrqk0xpgdwDettqWQWsiGlfsyM7/Ai4W3DQ+jCERhWYvvb+I0GesCEgv5jIGodRYW0=
  on:
    tags: true
    branch: master
    repo: kei-ito/middleware-static-livereload
