export const defaultContentTypes = {
    'image/png': ['.png'],
    'image/jpeg': ['.jpg', '.jpeg'],
    'image/svg+xml': ['.svg'],
    'image/tiff': ['.tiff'],
    'image/heif': ['.heif'],
    'image/heic': ['.heic'],
    'text/javascript; charset=UTF-8': ['.js'],
    'text/css': ['.css'],
    'font/otf': ['.otf'],
    'font/ttf': ['.ttf'],
    'font/woff': ['.woff'],
    'font/woff2': ['.woff2'],
    'text/html; charset=UTF-8': ['.html', '.htm'],
    'text/plain; charset=UTF-8': ['.txt', '.log'],
    'application/json': ['.json'],
    'image/vnd.microsoft.icon': ['.ico'],
};
