name: Test
on:
  - push
  - pull_request
jobs:
  CheckRenovate:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        node:
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g renovate
      - run: renovate-config-validator
  Setup:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 14.x
    steps:
      - run: git config --global core.autocrlf false
      - run: git config --global core.eol lf
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
  Test:
    runs-on: ${{ matrix.os }}
    needs:
      - Setup
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 14.x
          - 12.x
    steps:
      - run: git config --global core.autocrlf false
      - run: git config --global core.eol lf
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci --offline
      - run: npm run build
      - run: npx c8 npm test
      - run: npx c8 report --reporter=text-lcov > coverage.lcov
      - uses: codecov/codecov-action@v1
  TestClient:
    if: ${{ contains(github.ref, 'master') || contains(github.ref, 'tags/v') || github.event_name == 'pull_request' }}
    runs-on: ${{ matrix.os }}
    needs:
      - Setup
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        node:
          - 14.x
    environment: test
    steps:
      - run: git config --global core.autocrlf false
      - run: git config --global core.eol lf
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci --offline
      - run: npm run build
      - run: npm run test-client
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  Publish:
    if: contains(github.ref, 'tags/v')
    runs-on: ${{ matrix.os }}
    needs:
      - Test
      - TestClient
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        node:
          - 14.x
    environment: deployment
    steps:
      - run: git config --global core.autocrlf false
      - run: git config --global core.eol lf
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          registry-url: https://registry.npmjs.org
      - run: npm ci --offline
      - run: npm run build
      - run: npx cleanup-package-json --file package.json
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
